config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show, :destroy]
  resources :photos
  get "/staticpages/:staticpage" => "staticpages#show", as: :static
  root to: 'photos#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :prenom, presence: true
  validates :nom, presence: true
  validates :email, presence: true

  has_many :photos, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def to_s
    "#{prenom}"
end
end

app/controllers/User/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :prenom, :nom, :public, :bio, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :prenom, :nom, :public, :password, :bio, :password_confirmation, :current_password)
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
    @photos = @user.photos
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Utilisateur supprimé."
    redirect_to users_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_myprofile.html.erb
<div class="row justify-content-center mt-4">
  <div class="col-lg-3">

        <div id="bio">
          <p id="user_name"> <span id="green_underscore">_</span> <%= @user.prenom + " " + @user.nom %></p>
          <% if(@user.bio) %>
          <%= @user.bio %></div>
          <% end %>
      <p id="welcome">bienvenue sur votre profil</p>

      <%= link_to 'Modifier votre profil', edit_user_registration_path, id: 'btn_edit_profil' %>
  </div>

  <div class="col-lg-6">
    <div class="container feed">
      <div class="row">
        <div class="card-columns">

        </div>

        <div class="card-columns">
          <div class="card btn_add">
            <%= link_to image_tag('add.svg', alt: 'Bouton ajouter une nouvelle photo', id: 'img_btn_add') + 'Nouvelle photo', new_photo_path, id: 'btn_add' %>
          </div>
          <% @photos.reverse_each do |photo| %>
            <div class="card">
              <%= link_to photo do %>
                <img class="card-img-top" src="<%=  photo.file %>" alt="Card image cap">
              <% end %>
              <div class="card-body photo_content">
                <h5><%= link_to photo.title.truncate(60, separator: ' '), photo, :class => "card-title" %></h5>
                <p class="card-text"><%= photo.content.truncate(255, separator: ' ') %></p>
                  <% if user_signed_in? && photo.user_id == current_user.id %>
                  <div class="btn_card">
                    <%= link_to image_tag('trash.png', alt: 'Crayon', class: 'btn_card_edit'), photo, method: :delete %>
                    <%= link_to image_tag('edit.png', alt: 'Poubelle', class: 'btn_card_trash'), edit_photo_path(photo) %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_nopublic.html.erb
<h1>Veuillez réessayer</h1>
<p>Désolé, ce profil ne semble pas être public...</p>

app/views/users/_public.html.erb
<div class="row justify-content-center mt-4">
  <div class="col-lg-3">
        <div id="bio">
           <p id="user_name"> <span id="green_underscore">_</span> <%= @user.prenom + " " + @user.nom %></p>
            <% if(!@user.bio.blank?) %>
            <%= @user.bio %>
            <% end %>
  </div></div>

  <div class="col-lg-6">
    <div class="container feed">
      <div class="row">
        <div class="card-columns">
          <% if(user_signed_in? && current_user.admin) %>
            <%= link_to 'Supprimer', user_path(@user), method: :delete, data: { confirm: "Etes vous de sur de supprimer " + @user.prenom + " " + @user.nom + " des utilisateurs ?"} %>
          <% end %>
          <% @photos.reverse_each do |photo| %>
          <div class="card">
            <%= link_to photo do %>
            <img class="card-img-top" src="<%=  photo.file %>" alt="Card image cap">
            <% end %>
            <div class="card-body photo_content">
              <h5><%= link_to photo.title.truncate(60, separator: ' '), photo, :class => "card-title" %></h5>
              <p class="card-text"><%= photo.content.truncate(255, separator: ' ') %></p>
            </div>
          </div>
          <% end %>
       </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% if(current_user.admin == true) %>
  <h1>Gestion des utilisateurs :</h1>

  <table>
      <thead>
          <tr>
              <th>ID</th>
              <th>Email</th>
              <th>Prenom</th>
              <th>Nom</th>
              <th>Crée le</th>
              <th>Publique</th>
              <th>Admin</th>
          </tr>
      </thead>
      <% @users.each do |user| %>
      <tbody>
          <tr>
              <td><%=user.id%></td>
              <td><%=user.email%></td>
              <td><%=user.prenom%></td>
              <td><%=user.nom%></td>
              <td><%=user.created_at%></td>
              <td><%=user.public%></td>
              <td><%=user.admin%></td>
              <td><%= link_to 'Afficher', user %></td>
              <td></td>
              <td><%= link_to 'Supprimer', user_path(user), method: :delete, data: { confirm: "Etes vous de sur de supprimer " + user.prenom + " " + user.nom + " des utilisateurs ?"} %></td>
          </tr>
          <% end %>
      </tbody>
  </table>


<% end %>

app/views/users/show.html.erb
<% if user_signed_in? && @user == current_user %>
  <%= render 'myprofile' %>
<% elsif(@user.public == true) %>
  <%= render 'public' %>
<% elsif(@user.public == false) %>
  <%= render 'nopublic'  %>
<% else %>
<%= render 'unexist' %>
<% end %>