config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show, :destroy]
  resources :photos
  get "/staticpages/:staticpage" => "staticpages#show", as: :static
  root to: 'photos#index'
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :date, presence: true
  validates :long, presence: true
  validates :lat, presence: true
  belongs_to :user
  mount_uploader :file, FileUploader
  # validates :file, :presence => true

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json

  def index
    @dbphotos = Photo.all
    @photos = Photo.order(:id).page(params[:page]).per(15)
  end


  # def store
  #   # upload image to cloudinary
  #   @value = Cloudinary::Uploader.upload(params[:image])

  #   # create a new post object and save to db
  #   @photo = Photo.new({:link => @value['secure_url'], :caption => params[:caption]})

  #  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    if user_signed_in?
      @photo = Photo.new
    else
     redirect_to new_user_session_path
    end

  end

  # GET /photos/1/edit
  def edit
    if current_user.id == @photo.user_id or current_user.admin
    else redirect_to new_user_session_path
    end
  end

  # POST /photos
  # POST /photos.json
  def create
    if user_signed_in?
      @photo = Photo.new(photo_params)
      @photo.user_id = current_user.id
      @photo.save
    end

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Votre photo a été créée avec succès.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    if current_user.id == @photo.user_id
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Votre photo a été modifiée avec succès.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
    else redirect_to new_user_session_path
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @user = @photo.user
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'Votre photo a bien été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :content, :long, :lat, :date, :user_id, :file)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="row justify-content-center">
      <div class="col-lg-6 form_photo">
        <h1 id="edit_photo">votre photo :</h1>
        <% if !@photo.file.blank? %>
        <div class="edit_photo_box"><img src=" <%= @photo.file %> " alt="@photo.title"></div>
        <% end %>
        <div class="field_img">
          <%= form.file_field :file, onchange: "validateFiles(this);", data: { max_file_size: 5.megabytes}, required: true %>
          <%= form.hidden_field :file_cache %>
          <br> Votre photo ne doit pas dépasser 5Mo

        </div>

        <div class="field_img">
          <%= form.text_field :title, id: :photo_title, placeholder: "Titre", :required => true %>
        </div>

        <div class="field_img">
          <%= form.text_area :content, id: :photo_content, placeholder: "J'écris mon récit...", :required => true %>
        </div>

        <div class="field_img">
          <%= form.text_field :long, id: :photo_long, :required => true %>
        </div>

        <div class="field_img">
          <%= form.text_field :lat, id: :photo_lat, :required => true %>
        </div>

        <div class="field_img date">
          Photo prise le
          <%= form.date_select :date, id: :photo_date, :required => true %>
        </div>

        <div class="actions">
          <%= form.submit "Partagez-moi !", id: :btn_new %>
        </div>

      </div>

      <div class="col-lg-6 map">
        <div id="bg_opacity"><p id="btn_map">Indiquez le lieu</p></div>
        <div id="mapid" class="map_add">

        </div>
      </div>
    </div>




<% end %>
<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
   integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
   crossorigin=""></script>

<script>

  var map = new L.Map('mapid').setView([44.84561111, -0.58027778], 6);

 L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}{r}.{ext}', {
    attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
    maxZoom: 18,
    minZoom: 8,
    ext: 'png'
 }).addTo(map);
 map.attributionControl.setPrefix('');

var southWest = L.latLng(42.18155760646617, -1.90),
northEast = L.latLng(47.59346179538875, 3.6);
var bounds = L.latLngBounds(southWest, northEast);

map.setMaxBounds(bounds);
map.on('drag', function(){
  map.panInsideBounds(bounds, { animate: false});
});


 var marker = {};

 function addMarker(e){

  if(marker != undefined){
    map.removeLayer(marker);
  }


  marker = new L.marker(e.latlng).addTo(map);
    document.getElementById('photo_long').value = e.latlng.lng;
    document.getElementById('photo_lat').value = e.latlng.lat;

}

 map.on('click', addMarker);
</script>

app/views/photos/_form_edit.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="row justify-content-center">
      <div class="col-lg-6 form_photo">
        <h1 id="edit_photo">votre photo :</h1>
        <% if !@photo.file.blank? %>
        <div class="edit_photo_box"><img src=" <%= @photo.file %> " alt="@photo.title"></div>
        <% end %>
        <div class="field_img">
          <%= form.file_field :file, onchange: "validateFiles(this);", data: { max_file_size: 5.megabytes} %>
          <%= form.hidden_field :file_cache %>
          <br> Votre photo ne doit pas dépasser 5Mo

        </div>

        <div class="field_img">
          <%= form.text_field :title, id: :photo_title, placeholder: "Titre", :required => true %>
        </div>

        <div class="field_img">
          <%= form.text_area :content, id: :photo_content, placeholder: "J'écris mon récit...", :required => true %>
        </div>

        <div class="field_img">
          <%= form.text_field :long, id: :photo_long, :required => true %>
        </div>

        <div class="field_img">
          <%= form.text_field :lat, id: :photo_lat, :required => true %>
        </div>

        <div class="field_img date">
          Photo prise le
          <%= form.date_select :date, id: :photo_date, :required => true %>
        </div>

        <div class="actions">
          <%= form.submit "Partagez-moi !", id: :btn_new %>
        </div>

      </div>

      <div class="col-lg-6 map">
        <div id="mapid" class="map_add">

        </div>
      </div>
    </div>




<% end %>
<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
   integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
   crossorigin=""></script>

<script>

  var map = new L.Map('mapid').setView([44.84561111, -0.58027778], 6);

 L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}{r}.{ext}', {
    attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
    maxZoom: 18,
    minZoom: 8,
    ext: 'png'
 }).addTo(map);
 map.attributionControl.setPrefix('');

var southWest = L.latLng(42.18155760646617, -1.90),
northEast = L.latLng(47.59346179538875, 3.6);
var bounds = L.latLngBounds(southWest, northEast);

map.setMaxBounds(bounds);
map.on('drag', function(){
  map.panInsideBounds(bounds, { animate: false});
});


 var marker = {};

 function addMarker(e){

  if(marker != undefined){
    map.removeLayer(marker);
  }


  marker = new L.marker(e.latlng).addTo(map);
    document.getElementById('photo_long').value = e.latlng.lng;
    document.getElementById('photo_lat').value = e.latlng.lat;

}

 map.on('click', addMarker);
</script>

app/views/photos/edit.html.erb
<% content_for :title, "La carte & le territoire - Modifier votre photo" %>
<%= link_to image_tag('arrow.svg', alt: 'bouton retour', id: 'back_img'), photos_path, id: 'back' %>



<%= render 'form_edit', photo: @photo %>


<script>

    var long = <%= @photo.long %>;
    var lat = <%= @photo.lat %>;
    var icon = L.icon({
      iconUrl: '<%= @photo.file %>',
      iconSize: [25, 25],
    });
    var markerLocation = new L.LatLng(lat, long);
    var marker = new L.Marker(markerLocation, {icon: icon});
    map.addLayer(marker);

</script>

app/views/photos/index.html.erb
<% content_for :title, "La carte & le territoire" %>


  <div id="mapid"></div>

  <div id="notice"><%= notice %></div>

<div class="container feed">
  <div class="row">

    <div class="card-columns">
<% @photos.order(:id).reverse_each do |photo| %>

  <div class="card">
    <a href="photos/<%= photo.id %>">
    <img class="card-img-top" src="<%=  photo.file %>" alt="<%= photo.title %>">
    </a>
    <div class="card-body photo_content">
      <h5><%= link_to photo.title.truncate(120, separator: ' '), photo, :class => "card-title" %></h5>
      <p class="card-text"><%= photo.content.truncate(255, separator: ' ') %></p>
      <% if(user_signed_in? && current_user.admin) %>
        <%= link_to 'Modifier', edit_photo_path(photo) %>
        <%= link_to 'Supprimer', photo, method: :delete %>
      <% end %>
    </div>
  </div>
    <% end %>
       </div>
         <%= paginate @photos, theme: 'twitter-bootstrap-4', class: "navpagination" %>
  </div>
</div>

<br>
<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
   integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
   crossorigin=""></script>

<script>
  var map = new L.Map('mapid').setView([44.84561111, -0.58027778], 6);

 L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}{r}.{ext}', {
    attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
    maxZoom: 18,
    minZoom: 8,
    ext: 'png'
 }).addTo(map);
 map.attributionControl.setPrefix('');

var southWest = L.latLng(43.18155760646617, -5.90),
northEast = L.latLng(47.69346179538875, 5.3);
var bounds = L.latLngBounds(southWest, northEast);

map.setMaxBounds(bounds);
map.on('drag', function(){
  map.panInsideBounds(bounds, { animate: false});
});

 // Define an array. This could be done in a seperate js file.
 // This tidy formatted section could even be generated by a server-side script
 // or fetched seperately as a jsonp request.



<% @dbphotos.each do |photo| %>
    var long = <%= photo.long %>;
    var lat = <%= photo.lat %>;
    var icon = L.icon({
      iconUrl: '<%= photo.file %>',
      iconSize: [25, 25],
    });
    var markerLocation = new L.LatLng(lat, long);
    var marker = new L.Marker(markerLocation, {icon: icon});
    map.addLayer(marker);

    marker.on("click", function (event) {
    var clickedMarker = event.layer;
    document.location.href="photos/<%= photo.id %>";
});

<% end %>

</script>

app/views/photos/new.html.erb
<% content_for :title, "La carte & le territoire - Ajouter une photo" %>

<%= render 'form', photo: @photo %>

<%= link_to image_tag('arrow.svg', alt: 'bouton retour', id: 'back_img'), photos_path, id: 'back' %>

<script>

  $("#btn_new").click(function(){
    if(marker != undefined){
      $("#btn_map").animate({"left": "-=30px"}, 100, "linear" );
      $("#btn_map").animate({"left": "+=60px"}, 100, "linear" );
      $("#btn_map").animate({"left": "-=30px"}, 100, "linear" );

    }
  });

  $("#btn_map").click(function(){
    $("#btn_map").css({ "display": "none"});
    $("#bg_opacity").css({ "display": "none"});
  });

  $("#bg_opacity").click(function(){
    $("#btn_map").css({ "display": "none"});
    $("#bg_opacity").css({ "display": "none"});
  });

</script>

app/views/photos/show.html.erb
<% content_for :title, "La carte & le territoire - Fiche de la photo" %>

<div id="notice"><%= notice %></div>

<%= link_to image_tag('arrow.svg', alt: 'bouton retour', id: 'back_img'), photos_path, id: 'back' %>
<div class="container">
  <div class="row showrow">
    <div class="col-md-6">
      <%= image_tag @photo.file.url, class: 'img-fluid', id: 'img_fluid' %>
      <p class="userlink">Photo prise par <%= link_to_if @photo.user.public, @photo.user, @photo.user %></p>

    </div>
    <div class="col-md-5 offset-md-1">
      <h1><%= @photo.title.truncate(60, separator: ' ') %></h1>
        <p class="date">Photo prise le : <%= @photo.date %> </p>
        <p><%= @photo.content %></p>
        <% if user_signed_in? && current_user.admin || user_signed_in? && current_user == @photo.user %>
        <div class="btn">
          <%= link_to 'Modifier', edit_photo_path(@photo) %>
          <% if current_user == @photo.user || current_user.admin %>
            <%= link_to 'Supprimer', @photo, method: :delete, data: {confirm: 'Etes vous sur ?'} %>
          <% end %>
        </div>
        <% end %>
        <div id="content_map">
          <div id="mapid">
        </div>
        </div>

    </div>
  </div>
</div>




<div class="modal" id="myModal">
  <div class="modal-content" id="content_img_modal">
     <span class="close_modal">&times;</span>
      <%= image_tag @photo.file.url, class: 'img-fluid', id: 'img_modal' %>
  </div>
</div>

<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
        integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
        crossorigin=""></script>
<script>
  var map = new L.Map('mapid').setView([44.84561111, -0.58027778], 6);

 L.tileLayer('https://stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}{r}.{ext}', {
    attribution: '&copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
    maxZoom: 18,
    minZoom: 7.5,
    ext: 'png'
 }).addTo(map);
 map.attributionControl.setPrefix('');

var southWest = L.latLng(43.18155760646617, -2.90),
northEast = L.latLng(46.99346179538875, 4.3);
var bounds = L.latLngBounds(southWest, northEast);

map.setMaxBounds(bounds);
map.on('drag', function(){
  map.panInsideBounds(bounds, { animate: false});
});

    var long = <%= @photo.long %>;
    var lat = <%= @photo.lat %>;
    var popupText = "<%= @photo.title %>";
    var icon = L.icon({
      iconUrl: '<%= @photo.file %>',
      iconSize: [45, 45]
    });
    var markerLocation = new L.LatLng(lat, long);
    var marker = new L.Marker(markerLocation, {icon: icon});
    map.addLayer(marker);

    marker.bindPopup(popupText);

  var modal = document.getElementById('myModal');

  // Get the image and insert it inside the modal - use its "alt" text as a caption
  var img = document.getElementById('img_fluid');
  var modalImg = document.getElementById("content_img_modal");
  img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
  }

  // Get the <span> element that closes the modal
  var span = document.getElementsByClassName("close_modal")[0];

  // When the user clicks on <span> (x), close the modal
  span.onclick = function() {
    modal.style.display = "none";
  }


</script>