config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:index, :show, :destroy]
  resources :photos
  get "/staticpages/:staticpage" => "staticpages#show", as: :static
  root to: 'photos#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
          integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
          crossorigin=""/>
    <%= favicon_link_tag asset_path('logo_carte-territoire.png') %>
          <script
  src="http://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

  </head>
<body>

   <header>
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="d-flex flex-grow-1">
        <span class="w-100 d-lg-none d-block"></span>
        <a class="navbar-brand-two mx-auto d-lg-none d-inline-block" href="#">
            <%= link_to image_tag("logo.png", alt: "logo"), root_path, class: 'navbar-brand' %>
        </a>
        <div class="w-100 text-right">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
    <div class="collapse navbar-collapse flex-grow-1 text-right" id="myNavbar">
        <ul class="navbar-nav ml-auto flex-nowrap">
          <li class="nav-item">
                <%= link_to "Nouvelle photo",new_photo_path, class: "nav-link m-2 menu-item" %>
            </li>
             <li class="nav-item">
                <%= link_to "Notre projet",static_path(staticpage: 'about'), class: "nav-link m-2 menu-item" %>
            </li> <!--
            <li class="nav-item">
              <%= link_to "Nos expositions",static_path(staticpage: 'exposition'), class: "nav-link m-2 menu-item" %>
            </li>
            <li class="nav-item">
              <%= link_to "Vos questions",static_path(staticpage: 'question'), class: "m-2 nav-link menu-item" %>
            </li> -->
               <% if user_signed_in?%>
                <% if current_user.admin %>
                  <li class="nav-item">
                    <%= link_to "Gestion utilisateurs",users_path, class: "nav-link m-2 account menu-item" %>
                  </li>
                <% end %>
                <li class="nav-item">
                    <%= link_to "Profil",user_path(current_user), class: "nav-link m-2 account menu-item" %>
                  </li>
                  <li class="nav-item">
               <%= link_to "Déconnexion",destroy_user_session_path, method: :delete, class: "nav-link m-2 account menu-item" %>
            </li>
             <% else %>
             <li class="nav-item">
                <%= link_to "Inscription",new_user_registration_path, class: "nav-link m-2 account menu-item" %>
            </li>
            <li class="nav-item">
                <%= link_to "Connexion",new_user_session_path, class: "nav-link m-2 account menu-item" %>
            </li>
            <% end %>

        </ul>
    </div>
</nav>

     </header>

  <main class="content">
    <%= yield %>
    <div class="push"></div>
  </main>
  <!-- Footer -->

<footer class="footer py-3">
  <div class="row">
    <div class="col-md-12">
    <%= link_to image_tag("logo-associe.png", :alt => "logo", class:'logo'), href="https://www.lesassocies.net/" %>
  </div>
<!--     <div class="col-md-3">
      <ul class="list-unstyled text-small">
        <li>Nos partenaires</li>
        <li>Conditions générales</li>
      </ul>
    </div>
    <div class="col-md-3">
      <ul class="list-unstyled text-small">
        <li>Contact</li>
        <li>
                <%= link_to "Vos questions",static_path(staticpage: 'question') %>
        </li>
      </ul>
    </div> -->
  </div>
  <div class="row">
        <%= link_to image_tag("fb.png", :alt => "logo facebook", class:'rs'), href="https://www.facebook.com/LESASSOCIES.NET" %>
        <%= link_to image_tag("insta.png", :alt => "logo instagram", class:'rs'), href="https://www.instagram.com/collectiflesassocies" %>
        <%= link_to image_tag("linkedin.png", :alt => "logo linkedin", class:'rs'), href="https://fr.linkedin.com/in/les-associés-bb6462110"%>
      </div>
</footer>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>